# Generated by Django 5.2.7 on 2025-11-20 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_guia', models.CharField(max_length=20, unique=True)),
                ('remitente_nombre', models.CharField(max_length=255)),
                ('remitente_telefono', models.CharField(max_length=50)),
                ('remitente_email', models.CharField(blank=True, max_length=255, null=True)),
                ('destinatario_nombre', models.CharField(max_length=255)),
                ('destinatario_telefono', models.CharField(max_length=50)),
                ('destinatario_email', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_envio', models.CharField(max_length=50)),
                ('peso', models.FloatField()),
                ('dimensiones', models.CharField(blank=True, max_length=255, null=True)),
                ('origen', models.CharField(max_length=255)),
                ('direccion_origen', models.CharField(max_length=255)),
                ('destino', models.CharField(max_length=255)),
                ('direccion_destino', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
