# Generated by Django 5.2.7 on 2025-11-22 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='envio',
            old_name='fecha_creacion',
            new_name='fecha_creado',
        ),
        migrations.RemoveField(
            model_name='envio',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='envio',
            name='origen',
        ),
        migrations.AddField(
            model_name='envio',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='envio',
            name='destinatario_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='envio',
            name='destinatario_nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='envio',
            name='destinatario_telefono',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='envio',
            name='dimensiones',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='envio',
            name='direccion_destino',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='envio',
            name='direccion_origen',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='envio',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='envio',
            name='remitente_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='envio',
            name='remitente_nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='envio',
            name='remitente_telefono',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='envio',
            name='tipo_envio',
            field=models.CharField(max_length=20),
        ),
    ]
