# Generated by Django 5.2.7 on 2025-11-27 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_soporterespuesta_autor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soporteticket',
            name='prioridad',
        ),
        migrations.AddField(
            model_name='soporteticket',
            name='correo',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
