# Generated by Django 5.2.7 on 2025-11-29 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_soporteticket_prioridad_soporteticket_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='soporteticket',
            name='prioridad',
            field=models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], default='Media', max_length=10),
        ),
        migrations.AlterField(
            model_name='soporteticket',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('Respondido', 'Respondido')], default='Pendiente', max_length=20),
        ),
    ]
