# Generated by Django 6.0 on 2025-12-09 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_soporteticket_prioridad_alter_soporteticket_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Zona/Ciudad',
                'verbose_name_plural': 'Zonas/Ciudades',
            },
        ),
        migrations.AlterModelOptions(
            name='envio',
            options={'verbose_name': 'Envío', 'verbose_name_plural': 'Envíos'},
        ),
        migrations.AddField(
            model_name='envio',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='envio',
            name='estado',
            field=models.CharField(choices=[('Creado', 'Creado'), ('Recogido', 'Recogido'), ('En Clasificación', 'En Clasificación'), ('En Ruta', 'En Ruta'), ('En Reparto', 'En Reparto'), ('Entregado', 'Entregado'), ('Excepción', 'Excepción'), ('Cancelado', 'Cancelado')], default='Creado', max_length=20),
        ),
        migrations.CreateModel(
            name='TrazaEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_nuevo', models.CharField(choices=[('Creado', 'Creado'), ('Recogido', 'Recogido'), ('En Clasificación', 'En Clasificación'), ('En Ruta', 'En Ruta'), ('En Reparto', 'En Reparto'), ('Entregado', 'Entregado'), ('Excepción', 'Excepción'), ('Cancelado', 'Cancelado')], max_length=50)),
                ('descripcion', models.TextField(verbose_name='Detalle del Evento')),
                ('ubicacion', models.CharField(max_length=100, verbose_name='Ubicación')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trazas', to='core.envio')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Traza del Envío',
                'verbose_name_plural': 'Trazas del Envío',
                'ordering': ['fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_volumetrico', models.IntegerField(default=5000, help_text='Divisor para Peso Volumétrico (L*A*H / Factor)')),
                ('costo_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('limite_peso_kg', models.DecimalField(decimal_places=2, default=5.0, help_text='Peso que cubre el costo base', max_digits=10)),
                ('costo_por_kg_extra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas_destino', to='core.zona')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas_origen', to='core.zona')),
            ],
            options={
                'verbose_name': 'Tarifa de Envío',
                'verbose_name_plural': 'Tarifas de Envío',
                'unique_together': {('origen', 'destino')},
            },
        ),
    ]
